version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    networks:
      - app-network
    restart: unless-stopped

  post-service:
    build: ./post-service
    container_name: post-service
    ports:
      - "3002:3002"
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"  # Changed from 80 to 8080
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - post-service
    networks:
      - app-network
    restart: unless-stopped