version: "3.8"
services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"

  post-service:
    build: ./post-service
    container_name: post-service
    ports:
      - "3002:3002"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - post-service

# version: "3.8"
# networks:
#   my-network:
#     driver: bridge

# services:
#   user-service:
#     build: ./user_service
#     container_name: users-backend-service
#     ports:
#       - "3001:3001"
#     networks:
#       - my-network

#   post-service:
#     build: ./post_service
#     container_name: post-backend-service
#     ports:
#       - "3002:3002"
#     networks:
#       - my-network

#   kong:
#     image: kong:3.6
#     environment:
#       KONG_DATABASE: "off"
#       KONG_DECLARATIVE_CONFIG: /kong.yml
#       KONG_PROXY_LISTEN: 0.0.0.0:8000
#       KONG_ADMIN_LISTEN: 0.0.0.0:8001
#     ports:
#       - "8000:8000" # Public API
#       - "8001:8001" # Admin API
#     volumes:
#       - ./kong/kong.yml:/kong.yml:ro
#     networks:
#       - my-network
